version: '3'

services:
  frontdoor:
    build: .
    environment:
      REDIS_HOST: redis
      MODULES: frontdoor
    ports:
      - 3000:3000
    depends_on:
      - estimation
      - worker
  estimation:
    build: .
    environment:
      REDIS_HOST: redis
      MODULES: estimation
    depends_on:
      - redis
  worker:
    build: .
    environment:
      REDIS_HOST: redis
      MODULES: worker
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
