---
apiVersion: v1
kind: Service
metadata:
  name: frontdoor
spec:
  type: NodePort
  selector:
    app: frontdoor
  ports:
    - port: 8080
      targetPort: frontdoor-port
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontdoor
  labels:
    app: frontdoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontdoor
  template:
    metadata:
      labels:
        app: frontdoor
    spec:
      containers:
        - name: frontdoor
          image: ivannosov/micro-services:v1.0
          env:
            - name: MODULES
              value: frontdoor
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
          ports:
            - containerPort: 3000
              name: frontdoor-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: estimation
  labels:
    app: estimation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estimation
  template:
    metadata:
      labels:
        app: estimation
    spec:
      containers:
        - name: estimation
          image: ivannosov/micro-services:v1.0
          env:
            - name: MODULES
              value: estimation
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ivannosov/micro-services:v1.0
          env:
            - name: MODULES
              value: worker
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: redis-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
              name: redis-port
